name: Update README Countdown

on:
  schedule:
    - cron: "0 21 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README
        run: |
          BD_MONTH=10  # October
          BD_DAY=20

          TODAY=$(date -u +%Y-%m-%d)  # Get current date in UTC
          TARGET_DATE=$(date -d "$(date -u +%Y)-$BD_MONTH-$BD_DAY" +%Y-%m-%d 2>/dev/null || date -j -v+0d -f "%Y-%m-%d" "$(date -u +%Y)-$BD_MONTH-$BD_DAY" +%Y-%m-%d)
          
          if [[ "$TODAY" > "$TARGET_DATE" ]]; then
            TARGET_DATE=$(date -d "$(($(date -u +%Y) + 1))-$BD_MONTH-$BD_DAY" +%Y-%m-%d 2>/dev/null || date -j -v+1y -f "%Y-%m-%d" "$(date -u +%Y)-$BD_MONTH-$BD_DAY" +%Y-%m-%d)
          fi

          MONTHS_LEFT=$(( ($(date -d "$TARGET_DATE" +%s) - $(date -d "$TODAY" +%s)) / 2628000 ))

          sed -i "s/{COUNTDOWN}/$MONTHS_LEFT months/" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update countdown in README" || exit 0  # Avoid commit if no changes
          git push
