name: Update README Countdown

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update README
        run: |
          BD_M=10
          BD_D=20
          TODAY=$(date -u +"%Y-%m-%d")
          YEAR=$(date -u +"%Y")
          TARGET_DATE=$(date -u +"%Y-%m-%d" -d "$YEAR-$BD_M-$BD_D")

          if [[ "$TODAY" > "$TARGET_DATE" ]]; then
            TARGET_DATE=$(date -u +"%Y-%m-%d" -d "$((YEAR + 1))-$BD_M-$BD_D")
          fi

          DAYS_LEFT=$(( ( $(date -d "$TARGET_DATE" +%s) - $(date -d "$TODAY" +%s) ) / 86400 ))
          MONTHS_LEFT=$(( $(date -d "$TARGET_DATE" +%m) - $(date -d "$TODAY" +%m) + (12 * ($(date -d "$TARGET_DATE" +%Y) - $(date -d "$TODAY" +%Y))) ))
          if [ $(date -d "$TARGET_DATE" +%d) -lt $(date -d "$TODAY" +%d) ]; then
            MONTHS_LEFT=$((MONTHS_LEFT - 1))
          fi
          DAYS_REMAINING=$(( ( $(date -d "$TARGET_DATE" +%s) - $(date -d "$TODAY +$MONTHS_LEFT month" +%s) ) / 86400 ))

          if [[ $MONTHS_LEFT -gt 0 ]]; then
            COUNTDOWN="$MONTHS_LEFT months $DAYS_REMAINING days"
          else
            COUNTDOWN="$DAYS_REMAINING days"
          fi

          sed -i -E "s/[0-9]+ months [0-9]+ days/{COUNTDOWN}/g" README.md
          sed -i -E "s/[0-9]+ days/{COUNTDOWN}/g" README.md
          sed -i "s/{COUNTDOWN}/$COUNTDOWN/" README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update countdown in README" || echo "No changes to commit"
          git push