name: Update README Countdown

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update README
        run: |
          BD_M=10
          BD_D=20
          
          TODAY=$(date -u +%Y-%m-%d)
          YEAR=$(date -u +%Y)
          TARGET="$YEAR-$BD_M-$BD_D"

          if [ "$(date -d "$TODAY" +%s)" -gt "$(date -d "$TARGET" +%s)" ]; then
            TARGET="$((YEAR + 1))-$BD_M-$BD_D"
          fi
          
          DIFF_DAYS=$(( ( $(date -d "$TARGET" +%s) - $(date -d "$TODAY" +%s) ) / 86400 ))

          M=0
          START_DATE="$TODAY"

          while [ "$(date -d "$START_DATE" +%s)" -lt "$(date -d "$TARGET" +%s)" ]; do
            NEXT_MONTH=$(date -d "$START_DATE +1 month" +%Y-%m-%d)
            if [ "$(date -d "$NEXT_MONTH" +%s)" -le "$(date -d "$TARGET" +%s)" ]; then
              M=$((M + 1))
              START_DATE=$NEXT_MONTH
            else
              break
            fi
          done

          REMAINING_DAYS=$(( ( $(date -d "$TARGET" +%s) - $(date -d "$START_DATE"