name: Update README Countdown

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update README
        run: |
          BD_M=10
          BD_D=20
          
          TODAY=$(date -u +%Y-%m-%d)
          YEAR=$(date -u +%Y)
          TARGET="$YEAR-$BD_M-$BD_D"

          if [[ "$TODAY" > "$TARGET" ]]; then
            TARGET="$((YEAR + 1))-$BD_M-$BD_D"
          fi
          
          DIFF_DAYS=$(( ( $(date -d "$TARGET" +%s) - $(date -d "$TODAY" +%s) ) / 86400 ))

          M=0
          D=$DIFF_DAYS
          START_DATE="$TODAY"

          while [[ "$START_DATE" < "$TARGET" ]]; do
            NEXT_MONTH=$(date -d "$START_DATE +1 month" +%Y-%m-%d)
            if [[ "$NEXT_MONTH" <= "$TARGET" ]]; then
              M=$((M + 1))
              START_DATE=$NEXT_MONTH
            else
              break
            fi
          done

          REMAINING_DAYS=$(( ( $(date -d "$TARGET" +%s) - $(date -d "$START_DATE" +%s) ) / 86400 ))

          C="$REMAINING_DAYS days"
          [ "$M" -gt 0 ] && C="$M months $REMAINING_DAYS days"

          sed -i -E "s/[0-9]+ months [0-9]+ days/{COUNTDOWN}/g" README.md
          sed -i -E "s/[0-9]+ days/{COUNTDOWN}/g" README.md
          sed -i "s/{COUNTDOWN}/$C/" README.md

      - name: Commit and push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update countdown in README" || exit 0
          git push