name: Update README Countdown

on:
  schedule:
  - cron: "0 * * * *" 
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update README
        run: |
          BD_M=10
          BD_D=20
          
          T=$(date -u +%Y-%m-%d)
          TD=$(date -d "$(date -u +%Y)-$BD_M-$BD_D" +%Y-%m-%d 2>/dev/null || date -j -v+0d -f "%Y-%m-%d" "$(date -u +%Y)-$BD_M-$BD_D" +%Y-%m-%d)
          
          if [[ "$T" > "$TD" ]]; then
            TD=$(date -d "$(($(date -u +%Y) + 1))-$BD_M-$BD_D" +%Y-%m-%d 2>/dev/null || date -j -v+1y -f "%Y-%m-%d" "$(date -u +%Y)-$BD_M-$BD_D" +%Y-%m-%d)
          fi

          S=$(( $(date -d "$TD" +%s) - $(date -d "$T" +%s) ))
          D=$(( S / 86400 ))
          M=$(( D / 30 ))
          RD=$(( D % 30 ))

          C="$D days"
          [ "$M" -gt 0 ] && C="$M months $RD days"

          sed -i "s/[0-9]\+ months [0-9]\+ days/{COUNTDOWN}/" README.md
          sed -i "s/[0-9]\+ days/{COUNTDOWN}/" README.md
          sed -i "s/{COUNTDOWN}/$C/" README.md

      - name: Commit and push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update countdown in README" || exit 0
          git push